--- 
title: "5702 Final Report : LendingClub"
author: "Cheng Yan(cy2479), Chengyi Chen(cc4506), Michi Liu(xl2904), Wen Fan(wf2255)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

1.1 Company and raw data introduction
  LendingClub is an American peer-to-peer lending company, headquartered in San Francisco, California. It was the first peer-to-peer lender to register its offerings as securities with the Securities and Exchange Commission (SEC), and to offer loan trading on a secondary market. LendingClub is the world's largest peer-to-peer lending platform.The company claims that $15.98 billion in loans had been originated through its platform up to December 31, 2015.
  
  LendingClub enables borrowers to create unsecured personal loans between $1,000 and $40,000. The standard loan period is three years. Investors can search and browse the loan listings on LendingClub website and select loans that they want to invest in based on the information supplied about the borrower, amount of loan, loan grade, and loan purpose. Investors make money from interest. LendingClub makes money by charging borrowers an origination fee and investors a service fee.
  
  The Lending Club Loan Data contains complete loan data for all loans issued through the 2007-2015,including the current loan status (Current, Late, Fully Paid, etc.) and latest payment information. The file containing loan data through the “present” contains complete loan data for all loans issued through the previous completed calendar quarter. Additional features include credit scores, number of finance inquiries, address including zip codes, and state, and collections among others. The file is a matrix of about 890 thousand observations and 74 variables. The size of this dataset is about 421M.

1.2. Questions we try to understand
  Below trends are being investigated :
    a. The geographical distribution of loans
    b. The time distuirbution of loans
    c. The growth of issued loans in terms of dollars and volume

1.3 Technology stack 
  We are leavening the python – flask, pandas and numpy to process and clean raw data. The outcome for our finding is not only stay in local but also shared to other people using AWS. Report